#dist: xenial
language: python
python:
  #- "3.4"
  #- "3.5"
  #- "3.5-dev"
  - "3.6"
  #- "3.6-dev"
  - "3.7-dev"
  #- "3.7"
# command to install dependencies
install:
  - pip install Pillow
  - pip install Pyside2
  - pip install pytest
  - pip install pytest-qt
  - export PYTHONPATH=$PYTHONPATH:$(pwd)/src
# command to run tests
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
  -
script:
  - pytest