language: python
python:     # will be tested on default linux system
  - "3.5"
  - "3.6"
  - "3.7"
  # specifically interesting, see here https://bugs.python.org/issue38688:
  - "3.8.0"
  - "3.8"
  - "3.8-dev"
  - "3.9-dev"

dist: xenial

matrix:
  include:
    - name: "Python on macOS"
      os: osx
      osx_image: xcode10.2  # Python 3.7.2 running on macOS 10.14.3
      language: shell       # 'language: python' is an error on Travis CI macOS
      install:
        - pip3 install coverage
        - pip3 install pytest
        - pip3 install pytest-cov
        - python3 setup.py install

    - name: "Python 3.8.0 on Windows"
      os: windows           # Windows 10.0.17134 N/A Build 17134
      language: shell       # 'language: python' is an error on Travis CI Windows
      before_install:
        - choco install python --version 3.8.0
        - python -m pip install --upgrade pip
      env: PATH=/c/Python38:/c/Python38/Scripts:$PATH

install:
    - pip3 install coverage
    - pip3 install pytest
    - pip3 install pytest-cov
    - python setup.py install

script:
  - pytest --cov=atraxiflow -v
